flowchart TB
        A[Admin]
        S[Secretaire]
        E[Enseignant]

        U1((Gérer utilisateurs))
        U2((Gérer enseignants))
        U3((Gérer cours/sequences/ressources))
        U4((Declarer une activité))
        U5((Valider une activité))
        U6((Consulter recap))
        U7((Générer exports))
        U8((Param Système))
        U9((Param année académique))
        U10((Gérer les taux horaires))
        U11((Enreg. activité pédago.))
        U12((Calculer volume horaire))
        U13((Consulter mes activités))


    A --> U1 & U2 & U3 & U5 & U7 & U8 & U5 & U9 & U10 & U11

    S --> U5 & U7 & U3 & U11

    E --> U4 & U6 & U11 & U13

    U11 -.->|utilise| U12
    U5 -.->|utilise| U12
    U4 -.->|utilise| U12
